sonar.projectKey=Portfy-project-team_Portfy-project-team
sonar.organization=portfy-project-team
sonar.projectName=Portfy Backend
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/prisma/**
sonar.host.url=https://sonarcloud.io
sonar.token=35708c36ea7a79a70a9f01ae069fcce840154e09